# Generated by Django 5.0.2 on 2024-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christite_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
